Develop
karan-pharate/ui-assignment pull request #1
Opened 2019-09-17 07:45 UTC by karan-pharate

2019-09-17 12:21 UTC, Shrikant9 requested changes

2019-09-17 12:21 UTC, Shrikant9 commented on style.css
> +}
Add configuration to your editor so it automatically adds new line at the end of file.
If you're using vscode, add `"files.insertFinalNewline": true` to the configuration.

2019-09-19 15:14 UTC, visha15l commented on websiteLayout/index.html
> +                <li><a href="">Offers</a></li>
use href="javascript:;"

2019-09-19 15:19 UTC, visha15l commented on cssGrid/style.css
> +.grid-container {
use prettier

2019-09-19 15:20 UTC, visha15l commented on css-assignments/position.html
> +        right: 0px;
you can omit write 0 instead of 0px

2019-09-20 12:55 UTC, visha15l approved these changes

2019-09-20 12:57 UTC, merged